

def test_something():
    raise Exception()
